# Generated by Django 3.2.5 on 2021-07-04 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_agent_agent_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='AgentProfile',
        ),
    ]
