# Generated by Django 3.2.5 on 2021-07-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='End_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Start_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point_name', models.CharField(max_length=500)),
                ('pickup_point', models.ManyToManyField(to='route.Pickup')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.end_point')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.start_point')),
            ],
        ),
    ]
