# Generated by Django 3.2.5 on 2021-07-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='start_point',
            name='pickup_point',
        ),
        migrations.AddField(
            model_name='start_point',
            name='pickup_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pickup',
        ),
    ]
