# Generated by Django 3.2.5 on 2021-07-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20210704_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='End_point',
            new_name='EndPoint',
        ),
        migrations.RenameModel(
            old_name='Start_point',
            new_name='StartPoint',
        ),
        migrations.RenameField(
            model_name='startpoint',
            old_name='pickup_name',
            new_name='pickup_Points',
        ),
    ]
