# Generated by Django 3.2.5 on 2021-07-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_auto_20210704_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('children_price', models.IntegerField(blank=True)),
                ('special_price', models.IntegerField(blank=True)),
                ('group_price_per_person', models.IntegerField(blank=True)),
                ('route_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
