# Generated by Django 3.2.5 on 2021-07-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Registrarion_number', models.CharField(max_length=100)),
                ('engine_no', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('chasis_no', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('owner_phone_no', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.category')),
            ],
        ),
    ]
