# Generated by Django 3.2.5 on 2021-07-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_category_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='Categories',
            new_name='category',
        ),
    ]
