# Generated by Django 3.2.5 on 2021-07-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_auto_20210704_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
